# Jekyll workshop-template evanwill
# https://github.com/evanwill/workshop-template
# based on minima theme https://github.com/jekyll/minima

# Notes: 
# - pages with "nav: true" in front matter will be in header nav
# - figure include for centered images, put file in images directory and use: {% include figure.html img="my-cat.jpg" alt="cat" caption="My cat" width="50%" %}

# Site settings
# title appears in the header
title: "Learning Representations for Multi-Robot Systems: Graph Neural Networks and Beyond"
# description and keywords for meta tags
description: "ICRA 2025"
keywords: "Multi-Robot Systems, Graph Neural Networks, Learning Representations"

# author settings for cc-by, appears in the footer
author: gnn-icra25
pub_year: 2024
github_username: gnn-icra25

# add the full url for the github repository
repo: "https://github.com/gnn-icra25.github.io"

# site urls
# Optional if using GitHub Pages! If building manually, these must be set correctly.
# When using github pages just leave these blank!
#
# add the url for the domain,
# on gh-pages follow the pattern: https://username.github.io 
url: https://gnn-icra25.github.io/
# add subsection of the domain,
# on gh-pages this is a / followed by the name of the repository
baseurl: 

# add google analytics if desired (optional)
# if blank, it will be ignored
# use JEKYLL_ENV=production on build command
google-analytics-id: 

# defaults (to simplify front matter)
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Build settings
markdown: kramdown
